project_id = "fiporvgykkrsdodggdvy"

[functions.notify-emergency]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.notify-ambulance-dispatch]
verify_jwt = false

[functions.notify-hospital-acceptance]
verify_jwt = false
